apiVersion: v1
kind: ConfigMap
metadata:
  name: region-config
  namespace: default
data:
  aws.default.region: eu-west-1
  game.server.queue.name:  gameserver-q-GSQueue-1KXJSM0ZNRYZU
  game.server.queue.url: https://eu-west-1.queue.amazonaws.com/294038920501/gameserver-q-GSQueue-1KXJSM0ZNRYZU
  spot.int.queue.url: https://eu-west-1.queue.amazonaws.com/294038920501/spotint-q-SpotQueue-4I1000FHS3V

